#!/bin/bash
#

if [ "$1" == "" ] || [ "$2" == "" ] || [ "$3" == "" ]
then
  echo "usage: wifi-up <SSID> <PASSWD> <CONNECTION NAME>"
else
  if [ "$2" == "-np" ]
  then
    nmcli dev wifi con "$1" name "$3"
  else
    nmcli dev wifi con "$1" password "$2" name "$3"
  fi
fi
