#!/bin/bash

pack_cnt="$(checkupdates | wc -l)"

download="\uf109"
thumbs_up="\uf164"

orange="#dd5500"
green="#00FF00"

color=""
msg=""

if [ $pack_cnt == "0" ]
then
    color=$green
    msg=" %{F$color}$thumbs_up%{F-} "
else
    color=$orange
    msg=" %{F$color}$download $pack_cnt%{F-} "
fi

echo -e $msg
