#!/bin/bash
#

ECHO=/bin/echo
CAT=/bin/cat
TEE=/usr/bin/tee

BACKLITEDIR=/sys/class/backlight/intel_backlight

ID=/usr/bin/id

if [[ $($ID -u) != 0 ]]
then
	$ECHO "please run as root"
	$ECHO "exiting..."
	exit
fi

MAXBRITE=15
CURBRITE=0

if [[ -d $BACKLITEDIR ]]
then
	typeset -i MAXBRITE=$($CAT $BACKLITEDIR/max_brightness)
	typeset -i CURBRITE=$($CAT $BACKLITEDIR/brightness)
else
	$ECHO "$BACKLITEDIR could not be found, using max-brightness of $MAXBRITE and current brightness of $CURBRITE"
fi

if [[ "$1" == "" ]]
then
	$ECHO "usage: set-brightness <level>"
	$ECHO "where <level> is between 0 and $MAXBRITE"
	$ECHO
	$ECHO "current brightness: $CURBRITE"
	exit
fi

ISINT='^-?[0-9]+$'

if ! [[ $1 =~ $ISINT ]]
then
	$ECHO "please provide an integer brightness value"
	$ECHO "argument read: $1"
	$ECHO "exiting..."
	exit
fi

if [[ $1 -ge $MAXBRITE ]] || [[ $1 -lt 0 ]]
then
	$ECHO "please provide a brightness value between 0 and $MAXBRITE"
	$ECHO "argument read: $1"
	$ECHO "exiting..."
	exit
else
	$ECHO "setting brightness to $1..."
	$TEE $BACKLITEDIR/brightness <<< $1
fi
